package com.briup.apps.poll.mapper;

import com.briup.apps.poll.bean.Teacher;
import com.briup.apps.poll.bean.TeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    long countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    Teacher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_teacher
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByPrimaryKey(Teacher record);
}