package com.briup.apps.poll.bean;

public class Option {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.label
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.name
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.score
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.question_id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.id
     *
     * @return the value of poll_option.id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.id
     *
     * @param id the value for poll_option.id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.label
     *
     * @return the value of poll_option.label
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.label
     *
     * @param label the value for poll_option.label
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.name
     *
     * @return the value of poll_option.name
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.name
     *
     * @param name the value for poll_option.name
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.score
     *
     * @return the value of poll_option.score
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.score
     *
     * @param score the value for poll_option.score
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.question_id
     *
     * @return the value of poll_option.question_id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.question_id
     *
     * @param questionId the value for poll_option.question_id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}