package com.briup.apps.poll.bean;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_question.id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_question.type
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_question.name
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.id
     *
     * @return the value of poll_question.id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.id
     *
     * @param id the value for poll_question.id
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.type
     *
     * @return the value of poll_question.type
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.type
     *
     * @param type the value for poll_question.type
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.name
     *
     * @return the value of poll_question.name
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.name
     *
     * @param name the value for poll_question.name
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}