package com.briup.apps.poll.mapper;

import com.briup.apps.poll.bean.Answer;
import com.briup.apps.poll.bean.AnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    long countByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int deleteByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int insertSelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    List<Answer> selectByExampleWithBLOBs(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    List<Answer> selectByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    Answer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int updateByExample(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int updateByPrimaryKeySelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbg.generated Fri Mar 01 18:02:40 CST 2019
     */
    int updateByPrimaryKey(Answer record);
}