package com.briup.apps.poll.mapper;

import com.briup.apps.poll.bean.School;
import com.briup.apps.poll.bean.SchoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    long countByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int deleteByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    List<School> selectByExampleWithBLOBs(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    List<School> selectByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    School selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByExample(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_school
     *
     * @mbg.generated Fri Mar 01 18:02:39 CST 2019
     */
    int updateByPrimaryKey(School record);
}